from _typeshed import Incomplete
from zope.interface import Attribute as Attribute, Interface as Interface, classImplements as classImplements

class ITimeDeltaClass(Interface):
    min: Incomplete
    max: Incomplete
    resolution: Incomplete

class ITimeDelta(ITimeDeltaClass):
    days: Incomplete
    seconds: Incomplete
    microseconds: Incomplete

class IDateClass(Interface):
    min: Incomplete
    max: Incomplete
    resolution: Incomplete
    def today() -> None: ...
    def fromtimestamp(timestamp) -> None: ...
    def fromordinal(ordinal) -> None: ...

class IDate(IDateClass):
    year: Incomplete
    month: Incomplete
    day: Incomplete
    def replace(year, month, day) -> None: ...
    def timetuple() -> None: ...
    def toordinal() -> None: ...
    def weekday() -> None: ...
    def isoweekday() -> None: ...
    def isocalendar() -> None: ...
    def isoformat() -> None: ...
    def ctime() -> None: ...
    def strftime(format) -> None: ...

class IDateTimeClass(Interface):
    min: Incomplete
    max: Incomplete
    resolution: Incomplete
    def today() -> None: ...
    def now(tz: Incomplete | None = ...) -> None: ...
    def utcnow() -> None: ...
    def fromtimestamp(timestamp, tz: Incomplete | None = ...) -> None: ...
    def utcfromtimestamp(timestamp) -> None: ...
    def fromordinal(ordinal) -> None: ...
    def combine(date, time) -> None: ...

class IDateTime(IDate, IDateTimeClass):
    year: Incomplete
    month: Incomplete
    day: Incomplete
    hour: Incomplete
    minute: Incomplete
    second: Incomplete
    microsecond: Incomplete
    tzinfo: Incomplete
    def date() -> None: ...
    def time() -> None: ...
    def timetz() -> None: ...
    def replace(year, month, day, hour, minute, second, microsecond, tzinfo) -> None: ...
    def astimezone(tz) -> None: ...
    def utcoffset() -> None: ...
    def dst() -> None: ...
    def tzname() -> None: ...
    def timetuple() -> None: ...
    def utctimetuple() -> None: ...
    def toordinal() -> None: ...
    def weekday() -> None: ...
    def isoweekday() -> None: ...
    def isocalendar() -> None: ...
    def isoformat(sep: str = ...) -> None: ...
    def ctime() -> None: ...
    def strftime(format) -> None: ...

class ITimeClass(Interface):
    min: Incomplete
    max: Incomplete
    resolution: Incomplete

class ITime(ITimeClass):
    hour: Incomplete
    minute: Incomplete
    second: Incomplete
    microsecond: Incomplete
    tzinfo: Incomplete
    def replace(hour, minute, second, microsecond, tzinfo) -> None: ...
    def isoformat() -> None: ...
    def strftime(format) -> None: ...
    def utcoffset() -> None: ...
    def dst() -> None: ...
    def tzname() -> None: ...

class ITZInfo(Interface):
    def utcoffset(dt) -> None: ...
    def dst(dt) -> None: ...
    def tzname(dt) -> None: ...
    def fromutc(dt) -> None: ...
