from zope.interface import Attribute

class Field(Attribute):
    def __init__(self, title='', description='', __name__='',
                 required=True, readonly=False, constraint=None, default=None,
                 defaultFactory=None, *args, **kwargs) -> None:
        ...

class MinMaxLen(object): ...
class Orderable(object): ...

class Text(MinMaxLen, Field): ...
class TextLine(Text): ...
class Password(TextLine): ...
class Bool(Field): ...
class Number(Orderable, Field): ...
class Complex(Number): ...
class Real(Complex): ...
class Rational(Real): ...
class Integral(Rational): ...
class Int(Integral): ...
class Object(Field): ...
