from typing import Any

class FieldProperty:
    def __init__(self, field, name=None): ...
    def __get__(self, inst, klass) -> Any: ...
    def queryValue(self, inst, default): ...
    def __set__(self, inst, value: Any): ...