from typing import Any

import _interface_coptimizations
import _zope_interface_coptimizations
adapter_hooks: list

class ClassProvidesBase(_interface_coptimizations.SpecificationBase):
    _cls: Any
    _implements: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __get__(self, instance, owner) -> Any: ...

class InterfaceBase(_interface_coptimizations.SpecificationBase):
    __ibmodule__: Any
    __name__: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def __adapt__(self, *args, **kwargs) -> Any: ...
    def __call__(self, *args, **kwargs) -> Any: ...
    def __eq__(self, other) -> bool: ...
    def __ge__(self, other) -> bool: ...
    def __gt__(self, other) -> bool: ...
    def __hash__(self) -> int: ...
    def __le__(self, other) -> bool: ...
    def __lt__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...

class LookupBase:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def adapter_hook(self, *args, **kwargs) -> Any: ...
    def changed(self, *args, **kwargs) -> Any: ...
    def lookup(self, *args, **kwargs) -> Any: ...
    def lookup1(self, *args, **kwargs) -> Any: ...
    def lookupAll(self, *args, **kwargs) -> Any: ...
    def queryAdapter(self, *args, **kwargs) -> Any: ...
    def subscriptions(self, *args, **kwargs) -> Any: ...

class ObjectSpecificationDescriptor:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def __get__(self, instance, owner) -> Any: ...

class SpecificationBase:
    _bases: Any
    _dependents: Any
    _implied: Any
    _v_attrs: Any
    __iro__: Any
    __sro__: Any
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def implementedBy(self, *args, **kwargs) -> Any: ...
    def isOrExtends(self, *args, **kwargs) -> Any: ...
    def providedBy(self, *args, **kwargs) -> Any: ...
    def __call__(self, *args, **kwargs) -> Any: ...

class VerifyingBase(_zope_interface_coptimizations.LookupBase):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def adapter_hook(self, *args, **kwargs) -> Any: ...
    def changed(self, *args, **kwargs) -> Any: ...
    def lookup(self, *args, **kwargs) -> Any: ...
    def lookup1(self, *args, **kwargs) -> Any: ...
    def lookupAll(self, *args, **kwargs) -> Any: ...
    def queryAdapter(self, *args, **kwargs) -> Any: ...
    def subscriptions(self, *args, **kwargs) -> Any: ...

def getObjectSpecification(*args, **kwargs) -> Any: ...
def implementedBy(*args, **kwargs) -> Any: ...
def providedBy(*args, **kwargs) -> Any: ...
