class Invalid(Exception): ...

class _TargetInvalid(Invalid):
    @property
    def interface(self): ...
    @property
    def target(self): ...

class DoesNotImplement(_TargetInvalid): ...

class BrokenImplementation(_TargetInvalid):
    @property
    def name(self): ...

class BrokenMethodImplementation(_TargetInvalid):
    @property
    def method(self): ...
    @property
    def mess(self): ...

class MultipleInvalid(_TargetInvalid):
    def __init__(self, interface, target, exceptions) -> None: ...
    @property
    def exceptions(self): ...

class InvalidInterface(Exception): ...
class BadImplements(TypeError): ...
