from _typeshed import Incomplete
from collections.abc import Generator
from typing import Iterator, Optional, Type, TypeVar, Tuple

T = TypeVar("T")


class _UnhashableComponentCounter:
    def __init__(self, otherdict) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, component, count) -> None: ...
    def __delitem__(self, component) -> None: ...

class _UtilityRegistrations:
    def __init__(self, utilities, utility_registrations) -> None: ...
    def registerUtility(self, provided, name, component, info, factory) -> None: ...
    def unregisterUtility(self, provided, name, component) -> None: ...

class Components:
    __name__: Incomplete
    __bases__: Incomplete
    def __init__(self, name: str = ..., bases=...) -> None: ...
    def __reduce__(self): ...
    def registerUtility(self, component: Incomplete | None = ..., provided: Incomplete | None = ..., name: str = ..., info: str = ..., event: bool = ..., factory: Incomplete | None = ...) -> None: ...
    def unregisterUtility(self, component: Incomplete | None = ..., provided: Incomplete | None = ..., name: str = ..., factory: Incomplete | None = ...): ...
    def registeredUtilities(self) -> Generator[Incomplete, None, None]: ...
    def queryUtility(self, provided: Type[T], name: str = ..., default: Incomplete | None = ...) -> Optional[T]: ...
    def getUtility(self, provided: Type[T], name: str = ...) -> T: ...
    def getUtilitiesFor(self, interface: Type[T]) -> Iterator[Tuple[str, T]]: ...
    def getAllUtilitiesRegisteredFor(self, interface): ...
    def registerAdapter(self, factory, required: Incomplete | None = ..., provided: Incomplete | None = ..., name: str = ..., info: str = ..., event: bool = ...) -> None: ...
    def unregisterAdapter(self, factory: Incomplete | None = ..., required: Incomplete | None = ..., provided: Incomplete | None = ..., name: str = ...): ...
    def registeredAdapters(self) -> Generator[Incomplete, None, None]: ...
    def queryAdapter(self, object, interface: Type[T], name: str = ..., default: Incomplete | None = ...) -> Optional[T]: ...
    def getAdapter(self, object, interface: Type[T], name: str = ...) -> T: ...
    def queryMultiAdapter(self, objects, interface: Type[T], name: str = ..., default: Incomplete | None = ...) -> Optional[T]: ...
    def getMultiAdapter(self, objects, interface: Type[T], name: str = ...) -> T: ...
    def getAdapters(self, objects, provided: Type[T]) -> Iterator[Tuple[str, T]]: ...
    def registerSubscriptionAdapter(self, factory, required: Incomplete | None = ..., provided: Incomplete | None = ..., name: str = ..., info: str = ..., event: bool = ...) -> None: ...
    def registeredSubscriptionAdapters(self) -> Generator[Incomplete, None, None]: ...
    def unregisterSubscriptionAdapter(self, factory: Incomplete | None = ..., required: Incomplete | None = ..., provided: Incomplete | None = ..., name: str = ...): ...
    def subscribers(self, objects, provided: Type[T]) -> T: ...
    def registerHandler(self, factory, required: Incomplete | None = ..., name: str = ..., info: str = ..., event: bool = ...) -> None: ...
    def registeredHandlers(self) -> Generator[Incomplete, None, None]: ...
    def unregisterHandler(self, factory: Incomplete | None = ..., required: Incomplete | None = ..., name: str = ...): ...
    def handle(self, *objects) -> None: ...
    def rebuildUtilityRegistryFromLocalCache(self, rebuild: bool = ...): ...

class UtilityRegistration:
    def __init__(self, registry, provided, name, component, doc, factory: Incomplete | None = ...) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class AdapterRegistration:
    def __init__(self, registry, required, provided, name, component, doc) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class SubscriptionRegistration(AdapterRegistration): ...

class HandlerRegistration(AdapterRegistration):
    def __init__(self, registry, required, name, handler, doc) -> None: ...
    @property
    def factory(self): ...
    provided: Incomplete
